<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Fetch summary by account code
$query = $this->db->query("
    SELECT
        `account_code`,
        COUNT(*) as transaction_count,
        SUM(`amount`) as total_amount,
        MIN(`date`) as first_transaction,
        MAX(`date`) as last_transaction
    FROM
        `tbl_general_journal`
    WHERE
        `date` BETWEEN '$from_date' AND '$to_date'
    GROUP BY
        `account_code`
    ORDER BY
        `account_code` ASC
");

$summaries = $query->getResultArray();

$total_amount_all = $this->db->query("
    SELECT COALESCE(SUM(`amount`),0) as total 
    FROM `tbl_general_journal` 
    WHERE `date` BETWEEN '$from_date' AND '$to_date'
")->getRow()->total;

$total_transactions = $this->db->query("
    SELECT COUNT(*) as total 
    FROM `tbl_general_journal` 
    WHERE `date` BETWEEN '$from_date' AND '$to_date'
")->getRow()->total;

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('General Journal Summary Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'GENERAL JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Summary Report by Account Code', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Summary Cards
$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(95, 10, 'Total Transactions: ' . $total_transactions, 1, 0, 'L');
$pdf->Cell(95, 10, 'Total Amount: PHP ' . number_format($total_amount_all, 2), 1, 1, 'L');
$pdf->Ln(5);

// Table Header
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(50, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(40, 8, '# of Transactions', 1, 0, 'C');
$pdf->Cell(50, 8, 'Total Amount', 1, 0, 'C');
$pdf->Cell(50, 8, 'Date Range', 1, 1, 'C');

$pdf->SetFont('Times', '', 9);

if(count($summaries) > 0) {
    foreach($summaries as $row) {
        $pdf->Cell(50, 7, $row['account_code'], 1, 0, 'L');
        $pdf->Cell(40, 7, $row['transaction_count'], 1, 0, 'C');
        $pdf->Cell(50, 7, number_format($row['total_amount'], 2), 1, 0, 'R');
        $date_range = date('m/d/Y', strtotime($row['first_transaction'])) . ' - ' . date('m/d/Y', strtotime($row['last_transaction']));
        $pdf->Cell(50, 7, $date_range, 1, 1, 'C');
    }
} else {
    $pdf->Cell(190, 7, 'NO RECORDS FOUND', 1, 1, 'C');
}

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(90, 8, 'GRAND TOTAL', 1, 0, 'R');
$pdf->Cell(40, 8, $total_transactions, 1, 0, 'C');
$pdf->Cell(60, 8, number_format($total_amount_all, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>