<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Fetch all entries with running balance
$query = $this->db->query("
    SELECT
        `date`,
        `transaction_id`,
        `journal_id`,
        `account_code`,
        `amount`
    FROM
        `tbl_general_journal`
    WHERE
        `date` BETWEEN '$from_date' AND '$to_date'
    ORDER BY
        `date` ASC,
        `journal_id` ASC
");

$entries = $query->getResultArray();

$total_amount = $this->db->query("
    SELECT COALESCE(SUM(`amount`),0) as total 
    FROM `tbl_general_journal` 
    WHERE `date` BETWEEN '$from_date' AND '$to_date'
")->getRow()->total;

$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('General Journal Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'GENERAL JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Main Journal Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Calculate equal column widths for landscape A4 (277mm available with 10mm margins)
// 6 columns: Date(35), Trans ID(55), Journal ID(30), Account Code(50), Amount(45), Running Balance(62)
// Total = 35+55+30+50+45+62 = 277mm

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(35, 8, 'Date', 1, 0, 'C');
$pdf->Cell(55, 8, 'Transaction ID', 1, 0, 'C');
$pdf->Cell(30, 8, 'Journal ID', 1, 0, 'C');
$pdf->Cell(50, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(45, 8, 'Amount (PHP)', 1, 0, 'C');
$pdf->Cell(62, 8, 'Running Balance', 1, 1, 'C');

// Data rows with running balance
$pdf->SetFont('Times', '', 9);
$running_balance = 0;

if(count($entries) > 0) {
    foreach($entries as $row) {
        $running_balance += $row['amount'];
        
        $pdf->Cell(35, 7, date('Y-m-d', strtotime($row['date'])), 1, 0, 'C');
        $pdf->Cell(55, 7, $row['transaction_id'], 1, 0, 'L');
        $pdf->Cell(30, 7, $row['journal_id'], 1, 0, 'C');
        $pdf->Cell(50, 7, $row['account_code'], 1, 0, 'L');
        $pdf->Cell(45, 7, number_format($row['amount'], 2), 1, 0, 'R');
        $pdf->Cell(62, 7, number_format($running_balance, 2), 1, 1, 'R');
    }
} else {
    $pdf->Cell(277, 7, 'NO RECORDS FOUND', 1, 1, 'C');
}

// Total row
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(170, 8, 'GRAND TOTAL', 1, 0, 'R');
$pdf->Cell(45, 8, number_format($total_amount, 2), 1, 0, 'R');
$pdf->Cell(62, 8, number_format($running_balance, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>