<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$year = $this->request->getPostGet('year');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($year)) {
    $year = date('Y');
}

$formattedDate = date('F j, Y', strtotime(date('Y-m-d')));

// Monthly summary
$monthly_data = [];

for($month = 1; $month <= 12; $month++) {
    $month_name = date('F', mktime(0, 0, 0, $month, 1));
    
    $query = $this->db->query("
        SELECT 
            COALESCE(SUM(`amount`),0) as total,
            COUNT(*) as count
        FROM `tbl_general_journal`
        WHERE YEAR(`date`) = '$year' 
        AND MONTH(`date`) = '$month'
    ");
    $result = $query->getRow();
    
    $monthly_data[$month] = [
        'name' => $month_name,
        'total' => $result->total,
        'count' => $result->count
    ];
}

// Yearly totals
$yearly_total = $this->db->query("
    SELECT COALESCE(SUM(`amount`),0) as total 
    FROM `tbl_general_journal` 
    WHERE YEAR(`date`) = '$year'
")->getRow()->total;

$yearly_count = $this->db->query("
    SELECT COUNT(*) as total 
    FROM `tbl_general_journal` 
    WHERE YEAR(`date`) = '$year'
")->getRow()->total;

$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Monthly General Journal Summary');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'GENERAL JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Monthly General Journal Summary', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Year: ' . $year, 0, 1, 'C');
$pdf->Ln(8);

// Yearly Summary Cards
$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(90, 10, 'Yearly Total Transactions: ' . $yearly_count, 1, 0, 'L');
$pdf->Cell(100, 10, 'Yearly Total Amount: PHP ' . number_format($yearly_total, 2), 1, 1, 'L');
$pdf->Ln(5);

// Monthly Summary Table
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(40, 8, 'Month', 1, 0, 'C');
$pdf->Cell(100, 8, 'Total Amount (PHP)', 1, 0, 'C');
$pdf->Cell(40, 8, 'Transactions', 1, 1, 'C');

$pdf->SetFont('Times', '', 9);

for($month = 1; $month <= 12; $month++) {
    $data = $monthly_data[$month];
    
    $pdf->Cell(40, 7, $data['name'], 1, 0, 'L');
    $pdf->Cell(100, 7, number_format($data['total'], 2), 1, 0, 'R');
    $pdf->Cell(40, 7, $data['count'], 1, 1, 'C');
}

// Yearly Totals Row
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(40, 8, 'YEARLY TOTAL', 1, 0, 'L');
$pdf->Cell(100, 8, number_format($yearly_total, 2), 1, 0, 'R');
$pdf->Cell(40, 8, $yearly_count, 1, 1, 'C');

// Monthly Trend Chart
$pdf->Ln(10);
$pdf->SetFont('Times', 'B', 11);
$pdf->Cell(0, 8, 'Monthly Journal Trend', 0, 1, 'L');
$pdf->Ln(4);

$pdf->SetFont('Times', '', 8);
$max_total = 0;
foreach($monthly_data as $data) {
    if($data['total'] > $max_total) $max_total = $data['total'];
}
$max_total = $max_total > 0 ? $max_total : 1;
$chart_width = 200;

for($month = 1; $month <= 12; $month++) {
    $data = $monthly_data[$month];
    $bar_width = ($data['total'] / $max_total) * $chart_width;
    $bar_width = max(5, min($chart_width, $bar_width));
    
    $pdf->Cell(30, 5, substr($data['name'], 0, 3), 0, 0, 'L');
    
    $x = $pdf->GetX();
    $y = $pdf->GetY();
    $pdf->Rect($x, $y + 1, $bar_width, 3, 'F');
    $pdf->SetXY($x + $chart_width + 5, $y);
    $pdf->Cell(40, 5, 'PHP ' . number_format($data['total'], 2), 0, 1, 'L');
}

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>