<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Get account types from Chart of Accounts
$account_types = [
    'ASSET' => 'Asset Accounts',
    'LIABILITY' => 'Liability Accounts',
    'EQUITY' => 'Equity Accounts',
    'REVENUE' => 'Revenue Accounts',
    'EXPENSE' => 'Expense Accounts'
];

$account_breakdown = [];
$total_all = 0;

foreach($account_types as $type_code => $type_name) {
    $query = $this->db->query("
        SELECT 
            COALESCE(SUM(gj.`amount`),0) as total,
            COUNT(*) as count
        FROM `tbl_general_journal` gj
        LEFT JOIN `tbl_chart_of_accounts` coa ON coa.account_code = gj.account_code
        WHERE coa.account_type = '$type_code'
        AND gj.`date` BETWEEN '$from_date' AND '$to_date'
    ");
    $result = $query->getRow();
    $account_breakdown[$type_code] = [
        'name' => $type_name,
        'total' => $result->total,
        'count' => $result->count
    ];
    $total_all += $result->total;
}

// Get accounts without type mapping
$query_other = $this->db->query("
    SELECT 
        gj.account_code,
        SUM(gj.`amount`) as total,
        COUNT(*) as count
    FROM `tbl_general_journal` gj
    LEFT JOIN `tbl_chart_of_accounts` coa ON coa.account_code = gj.account_code
    WHERE coa.account_type IS NULL
    AND gj.`date` BETWEEN '$from_date' AND '$to_date'
    GROUP BY gj.account_code
");
$other_accounts = $query_other->getResultArray();

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('General Journal Account Breakdown');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'GENERAL JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Account Breakdown Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Account Breakdown Table
$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(80, 8, 'Account Type', 1, 0, 'C');
$pdf->Cell(50, 8, 'Transactions', 1, 0, 'C');
$pdf->Cell(60, 8, 'Total Amount (PHP)', 1, 1, 'C');

$pdf->SetFont('Times', '', 9);

foreach($account_breakdown as $code => $data) {
    if($data['total'] > 0) {
        $pdf->Cell(80, 7, $data['name'] . ' (' . $code . ')', 1, 0, 'L');
        $pdf->Cell(50, 7, $data['count'], 1, 0, 'C');
        $pdf->Cell(60, 7, number_format($data['total'], 2), 1, 1, 'R');
    }
}

foreach($other_accounts as $other) {
    $pdf->Cell(80, 7, $other['account_code'], 1, 0, 'L');
    $pdf->Cell(50, 7, $other['count'], 1, 0, 'C');
    $pdf->Cell(60, 7, number_format($other['total'], 2), 1, 1, 'R');
}

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(130, 8, 'TOTAL', 1, 0, 'R');
$pdf->Cell(60, 8, number_format($total_all, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>