<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$report_date = $this->request->getPostGet('report_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($report_date)) {
    $report_date = date('Y-m-d');
}

$formattedReportDate = date('F d, Y', strtotime($report_date));

// Fetch daily cash disbursements
$query = $this->db->query("
    SELECT
        `date`,
        `transaction_id`,
        `journal_id`,
        `account_code`,
        `amount`,
        `payee`,
        `description`
    FROM
        `tbl_cash_disbursement_journal`
    WHERE
        `date` = '$report_date'
    ORDER BY
        `transaction_id` ASC
");

$disbursements = $query->getResultArray();

// Get totals per account code
$query_total = $this->db->query("
    SELECT
        `account_code`,
        COUNT(*) as transaction_count,
        SUM(`amount`) as total_amount
    FROM
        `tbl_cash_disbursement_journal`
    WHERE
        `date` = '$report_date'
    GROUP BY
        `account_code`
");

$account_totals = $query_total->getResultArray();

$total_all = $this->db->query("
    SELECT COALESCE(SUM(`amount`),0) as total 
    FROM `tbl_cash_disbursement_journal` 
    WHERE `date` = '$report_date'
")->getRow()->total;

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Daily Cash Disbursement Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'CASH DISBURSEMENT JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Daily Cash Disbursement Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date: ' . $formattedReportDate, 0, 1, 'C');
$pdf->Ln(8);

// Column Headers
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(25, 8, 'Date', 1, 0, 'C');
$pdf->Cell(45, 8, 'Transaction ID', 1, 0, 'C');
$pdf->Cell(20, 8, 'Journal ID', 1, 0, 'C');
$pdf->Cell(35, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(35, 8, 'Payee', 1, 0, 'C');
$pdf->Cell(35, 8, 'Amount (PHP)', 1, 1, 'C');

// Data rows
$pdf->SetFont('Times', '', 8);
$total = 0;

foreach($disbursements as $row) {
    $pdf->Cell(25, 7, date('Y-m-d', strtotime($row['date'])), 1, 0, 'C');
    $pdf->Cell(45, 7, $row['transaction_id'], 1, 0, 'L');
    $pdf->Cell(20, 7, $row['journal_id'], 1, 0, 'C');
    $pdf->Cell(35, 7, $row['account_code'], 1, 0, 'L');
    $pdf->Cell(35, 7, substr($row['payee'] ?? '-', 0, 20), 1, 0, 'L');
    $pdf->Cell(35, 7, number_format($row['amount'], 2), 1, 1, 'R');
    $total += $row['amount'];
}

// Total row
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(160, 8, 'GRAND TOTAL', 1, 0, 'R');
$pdf->Cell(35, 8, number_format($total, 2), 1, 1, 'R');

$pdf->Ln(8);

// Summary by Account Code
$pdf->SetFont('Times', 'B', 11);
$pdf->Cell(0, 8, 'Summary by Account Code', 0, 1, 'L');
$pdf->Ln(2);

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(60, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(50, 8, 'No. of Transactions', 1, 0, 'C');
$pdf->Cell(85, 8, 'Total Amount (PHP)', 1, 1, 'C');

$pdf->SetFont('Times', '', 9);

foreach($account_totals as $acc) {
    $pdf->Cell(60, 7, $acc['account_code'], 1, 0, 'L');
    $pdf->Cell(50, 7, $acc['transaction_count'], 1, 0, 'C');
    $pdf->Cell(85, 7, number_format($acc['total_amount'], 2), 1, 1, 'R');
}

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(110, 8, 'OVERALL TOTAL', 1, 0, 'R');
$pdf->Cell(85, 8, number_format($total_all, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>