<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Fetch all disbursements with running balance
$query = $this->db->query("
    SELECT
        `date`,
        `transaction_id`,
        `journal_id`,
        `account_code`,
        `amount`,
        `payee`
    FROM
        `tbl_cash_disbursement_journal`
    WHERE
        `date` BETWEEN '$from_date' AND '$to_date'
    ORDER BY
        `date` ASC,
        `journal_id` ASC
");

$disbursements = $query->getResultArray();

$total_amount = $this->db->query("
    SELECT COALESCE(SUM(`amount`),0) as total 
    FROM `tbl_cash_disbursement_journal` 
    WHERE `date` BETWEEN '$from_date' AND '$to_date'
")->getRow()->total;

$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Cash Disbursement Journal Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'CASH DISBURSEMENT JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Main Journal Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Column widths for landscape
// 6 columns: Date(30), Trans ID(50), Journal ID(25), Account Code(50), Payee(50), Amount(40), Running Balance(40)
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(30, 8, 'Date', 1, 0, 'C');
$pdf->Cell(50, 8, 'Transaction ID', 1, 0, 'C');
$pdf->Cell(25, 8, 'Journal ID', 1, 0, 'C');
$pdf->Cell(50, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(50, 8, 'Payee', 1, 0, 'C');
$pdf->Cell(35, 8, 'Amount (PHP)', 1, 0, 'C');
$pdf->Cell(35, 8, 'Running Balance', 1, 1, 'C');

// Data rows with running balance
$pdf->SetFont('Times', '', 9);
$running_balance = 0;

foreach($disbursements as $row) {
    $running_balance += $row['amount'];
    
    $pdf->Cell(30, 7, date('Y-m-d', strtotime($row['date'])), 1, 0, 'C');
    $pdf->Cell(50, 7, $row['transaction_id'], 1, 0, 'L');
    $pdf->Cell(25, 7, $row['journal_id'], 1, 0, 'C');
    $pdf->Cell(50, 7, $row['account_code'], 1, 0, 'L');
    $pdf->Cell(50, 7, substr($row['payee'] ?? '-', 0, 25), 1, 0, 'L');
    $pdf->Cell(35, 7, number_format($row['amount'], 2), 1, 0, 'R');
    $pdf->Cell(35, 7, number_format($running_balance, 2), 1, 1, 'R');
}

// Total row
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(205, 8, 'GRAND TOTAL', 1, 0, 'R');
$pdf->Cell(35, 8, number_format($total_amount, 2), 1, 0, 'R');
$pdf->Cell(35, 8, number_format($running_balance, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>