<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Get Chart of Accounts for expense mapping
$expense_categories = [
    '5010' => 'Cost of Goods Sold',
    '5020' => 'Rent Expense',
    '5030' => 'Utilities Expense',
    '5040' => 'Salaries Expense',
    '5050' => 'Supplies Expense',
    '5060' => 'Maintenance Expense',
    '5070' => 'Marketing Expense'
];

$expense_data = [];
$total_expense = 0;

foreach($expense_categories as $code => $name) {
    $query = $this->db->query("
        SELECT 
            COALESCE(SUM(`amount`),0) as total,
            COUNT(*) as count
        FROM `tbl_cash_disbursement_journal`
        WHERE `account_code` = '$code'
        AND `date` BETWEEN '$from_date' AND '$to_date'
    ");
    $result = $query->getRow();
    $expense_data[$code] = [
        'name' => $name,
        'total' => $result->total,
        'count' => $result->count
    ];
    $total_expense += $result->total;
}

// Get other account codes not in main categories
$query_other = $this->db->query("
    SELECT 
        `account_code`,
        SUM(`amount`) as total,
        COUNT(*) as count
    FROM `tbl_cash_disbursement_journal`
    WHERE `account_code` NOT IN ('5010','5020','5030','5040','5050','5060','5070')
    AND `date` BETWEEN '$from_date' AND '$to_date'
    GROUP BY `account_code`
");
$other_expenses = $query_other->getResultArray();

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Expense Breakdown Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'CASH DISBURSEMENT JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Expense Breakdown Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Expense Summary
$pdf->SetFont('Times', 'B', 11);
$pdf->Cell(0, 8, 'EXPENSE SUMMARY', 0, 1, 'L');
$pdf->Ln(2);

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(80, 8, 'Expense Category', 1, 0, 'C');
$pdf->Cell(50, 8, 'Transactions', 1, 0, 'C');
$pdf->Cell(60, 8, 'Total Amount (PHP)', 1, 1, 'C');

$pdf->SetFont('Times', '', 9);

foreach($expense_data as $code => $data) {
    if($data['total'] > 0) {
        $pdf->Cell(80, 7, $data['name'] . ' (' . $code . ')', 1, 0, 'L');
        $pdf->Cell(50, 7, $data['count'], 1, 0, 'C');
        $pdf->Cell(60, 7, number_format($data['total'], 2), 1, 1, 'R');
    }
}

foreach($other_expenses as $other) {
    $pdf->Cell(80, 7, $other['account_code'], 1, 0, 'L');
    $pdf->Cell(50, 7, $other['count'], 1, 0, 'C');
    $pdf->Cell(60, 7, number_format($other['total'], 2), 1, 1, 'R');
}

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(130, 8, 'TOTAL EXPENSES', 1, 0, 'R');
$pdf->Cell(60, 8, number_format($total_expense, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>