<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$account_code = $this->request->getPostGet('account_code');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Get account name
$account_name = '';
if(!empty($account_code)) {
    $acc_query = $this->db->query("SELECT account_name FROM tbl_chart_of_accounts WHERE account_code = '$account_code'");
    $acc = $acc_query->getRow();
    $account_name = $acc ? $acc->account_name : '';
}

// Fetch ledger entries
if(!empty($account_code)) {
    $query = $this->db->query("
        SELECT 
            date,
            transaction_id,
            journal_id,
            account_code,
            amount,
            description
        FROM tbl_general_journal
        WHERE account_code = '$account_code'
        AND date BETWEEN '$from_date' AND '$to_date'
        ORDER BY date ASC, journal_id ASC
    ");
} else {
    $query = $this->db->query("
        SELECT 
            date,
            transaction_id,
            journal_id,
            account_code,
            amount,
            description
        FROM tbl_general_journal
        WHERE date BETWEEN '$from_date' AND '$to_date'
        ORDER BY account_code ASC, date ASC, journal_id ASC
    ");
}
$entries = $query->getResultArray();

$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Ledger Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'LEDGER REPORT', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
if(!empty($account_code)) {
    $pdf->Cell(0, 6, 'Account: ' . $account_code . ' - ' . $account_name, 0, 1, 'C');
} else {
    $pdf->Cell(0, 6, 'All Accounts', 0, 1, 'C');
}
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Calculate column widths for landscape A4 (277mm available)
// 6 columns: Date(30), Trans ID(45), Journal ID(25), Account Code(40), Amount(45), Running Balance(45), Description(47)
// Total = 30+45+25+40+45+45+47 = 277mm

$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(30, 8, 'Date', 1, 0, 'C');
$pdf->Cell(45, 8, 'Transaction ID', 1, 0, 'C');
$pdf->Cell(25, 8, 'Journal ID', 1, 0, 'C');
$pdf->Cell(40, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(45, 8, 'Amount (PHP)', 1, 0, 'C');
$pdf->Cell(45, 8, 'Running Balance', 1, 0, 'C');
$pdf->Cell(47, 8, 'Description', 1, 1, 'C');

// Data rows
$pdf->SetFont('Times', '', 8);
$current_account = '';
$running_balance = 0;

foreach($entries as $row) {
    // Account separator
    if($current_account != $row['account_code']) {
        $current_account = $row['account_code'];
        $running_balance = 0;
        
        $pdf->SetFont('Times', 'B', 8);
        $pdf->SetFillColor(245, 245, 245);
        $pdf->Cell(277, 6, ' Account: ' . $row['account_code'], 1, 1, 'L', true);
        $pdf->SetFont('Times', '', 8);
    }
    
    $running_balance += $row['amount'];
    
    $pdf->Cell(30, 7, date('Y-m-d', strtotime($row['date'])), 1, 0, 'C');
    $pdf->Cell(45, 7, $row['transaction_id'], 1, 0, 'L');
    $pdf->Cell(25, 7, $row['journal_id'], 1, 0, 'C');
    $pdf->Cell(40, 7, $row['account_code'], 1, 0, 'L');
    $pdf->Cell(45, 7, number_format($row['amount'], 2), 1, 0, 'R');
    $pdf->Cell(45, 7, number_format($running_balance, 2), 1, 0, 'R');
    $pdf->Cell(47, 7, substr($row['description'] ?? '-', 0, 35), 1, 1, 'L');
}

if(count($entries) == 0) {
    $pdf->Cell(277, 10, 'NO RECORDS FOUND', 1, 1, 'C');
}

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>