<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// REVENUE from Cash Receipts Journal
$revenue_query = $this->db->query("
    SELECT 
        account_code,
        SUM(amount) as total
    FROM tbl_cash_receipts_journal
    WHERE date BETWEEN '$from_date' AND '$to_date'
    GROUP BY account_code
    ORDER BY account_code ASC
");
$revenues = $revenue_query->getResultArray();

$total_revenue = 0;
foreach($revenues as $rev) {
    $total_revenue += $rev['total'];
}

// EXPENSES from Cash Disbursement Journal
$expense_query = $this->db->query("
    SELECT 
        account_code,
        SUM(amount) as total
    FROM tbl_cash_disbursement_journal
    WHERE date BETWEEN '$from_date' AND '$to_date'
    GROUP BY account_code
    ORDER BY account_code ASC
");
$expenses = $expense_query->getResultArray();

$total_expense = 0;
foreach($expenses as $exp) {
    $total_expense += $exp['total'];
}

$net_income = $total_revenue - $total_expense;

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Income Statement');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'INCOME STATEMENT', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'For the Period Ended ' . $formattedTo, 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(10);

// REVENUE Section
$pdf->SetFont('Times', 'B', 11);
$pdf->Cell(140, 8, 'REVENUE', 0, 0, 'L');
$pdf->Ln(8);

$pdf->SetFont('Times', '', 10);
foreach($revenues as $rev) {
    $acc_query = $this->db->query("SELECT account_name FROM tbl_chart_of_accounts WHERE account_code = '{$rev['account_code']}'");
    $acc_name = $acc_query->getRow();
    $account_name = $acc_name ? $acc_name->account_name : $rev['account_code'];
    
    $pdf->Cell(100, 7, '  ' . $rev['account_code'] . ' - ' . substr($account_name, 0, 35), 0, 0, 'L');
    $pdf->Cell(90, 7, number_format($rev['total'], 2), 0, 1, 'R');
}

$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(140, 8, 'TOTAL REVENUE', 0, 0, 'R');
$pdf->Cell(50, 8, number_format($total_revenue, 2), 0, 1, 'R');
$pdf->Ln(8);

// EXPENSES Section
$pdf->SetFont('Times', 'B', 11);
$pdf->Cell(140, 8, 'EXPENSES', 0, 0, 'L');
$pdf->Ln(8);

$pdf->SetFont('Times', '', 10);
foreach($expenses as $exp) {
    $acc_query = $this->db->query("SELECT account_name FROM tbl_chart_of_accounts WHERE account_code = '{$exp['account_code']}'");
    $acc_name = $acc_query->getRow();
    $account_name = $acc_name ? $acc_name->account_name : $exp['account_code'];
    
    $pdf->Cell(100, 7, '  ' . $exp['account_code'] . ' - ' . substr($account_name, 0, 35), 0, 0, 'L');
    $pdf->Cell(90, 7, number_format($exp['total'], 2), 0, 1, 'R');
}

$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(140, 8, 'TOTAL EXPENSES', 0, 0, 'R');
$pdf->Cell(50, 8, number_format($total_expense, 2), 0, 1, 'R');
$pdf->Ln(10);

// NET INCOME Section
$pdf->SetFont('Times', 'B', 12);
if($net_income >= 0) {
    $pdf->SetTextColor(0, 128, 0);
    $pdf->Cell(140, 8, 'NET INCOME', 0, 0, 'R');
    $pdf->Cell(50, 8, number_format($net_income, 2), 0, 1, 'R');
} else {
    $pdf->SetTextColor(255, 0, 0);
    $pdf->Cell(140, 8, 'NET LOSS', 0, 0, 'R');
    $pdf->Cell(50, 8, number_format(abs($net_income), 2), 0, 1, 'R');
}
$pdf->SetTextColor(0, 0, 0);

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>