<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Fetch trial balance data
$query = $this->db->query("
    SELECT 
        gj.account_code,
        coa.account_name,
        coa.account_type,
        SUM(CASE WHEN gj.amount > 0 THEN gj.amount ELSE 0 END) as total_debits,
        SUM(CASE WHEN gj.amount < 0 THEN ABS(gj.amount) ELSE 0 END) as total_credits
    FROM tbl_general_journal gj
    LEFT JOIN tbl_chart_of_accounts coa ON coa.account_code = gj.account_code
    WHERE gj.date BETWEEN '$from_date' AND '$to_date'
    GROUP BY gj.account_code, coa.account_name, coa.account_type
    ORDER BY 
        CASE coa.account_type
            WHEN 'ASSET' THEN 1
            WHEN 'LIABILITY' THEN 2
            WHEN 'EQUITY' THEN 3
            WHEN 'REVENUE' THEN 4
            WHEN 'EXPENSE' THEN 5
        END,
        gj.account_code ASC
");

$trial_balance = $query->getResultArray();

$total_debits = 0;
$total_credits = 0;

$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Trial Balance Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'TRIAL BALANCE', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'As of ' . $formattedFrom . ' to ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Column Headers - Landscape
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(50, 8, 'Account Code', 1, 0, 'C');
$pdf->Cell(80, 8, 'Account Name', 1, 0, 'C');
$pdf->Cell(40, 8, 'Type', 1, 0, 'C');
$pdf->Cell(55, 8, 'Debit (PHP)', 1, 0, 'C');
$pdf->Cell(55, 8, 'Credit (PHP)', 1, 1, 'C');

// Data rows
$pdf->SetFont('Times', '', 9);

foreach($trial_balance as $row) {
    $debit = $row['total_debits'];
    $credit = $row['total_credits'];
    $total_debits += $debit;
    $total_credits += $credit;
    
    $pdf->Cell(50, 7, $row['account_code'], 1, 0, 'L');
    $pdf->Cell(80, 7, substr($row['account_name'] ?? $row['account_code'], 0, 35), 1, 0, 'L');
    $pdf->Cell(40, 7, $row['account_type'] ?? '-', 1, 0, 'C');
    $pdf->Cell(55, 7, number_format($debit, 2), 1, 0, 'R');
    $pdf->Cell(55, 7, number_format($credit, 2), 1, 1, 'R');
}

// Total row
$pdf->SetFont('Times', 'B', 9);
$pdf->Cell(170, 8, 'TOTAL', 1, 0, 'R');
$pdf->Cell(55, 8, number_format($total_debits, 2), 1, 0, 'R');
$pdf->Cell(55, 8, number_format($total_credits, 2), 1, 1, 'R');

// Status
$pdf->Ln(5);
$pdf->SetFont('Times', 'I', 9);
if(abs($total_debits - $total_credits) < 0.01) {
    $pdf->SetTextColor(0, 100, 0);
    $pdf->Cell(0, 6, 'STATUS: BALANCED - Debits equal Credits', 0, 1, 'L');
} else {
    $pdf->SetTextColor(255, 0, 0);
    $pdf->Cell(0, 6, 'STATUS: OUT OF BALANCE - Difference of PHP ' . number_format(abs($total_debits - $total_credits), 2), 0, 1, 'L');
}
$pdf->SetTextColor(0, 0, 0);

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>