<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Income breakdown by account code
$income_categories = [
    '4010-MEMBERSHIP' => 'Membership Fee Income',
    '4020-RETAIL' => 'Retail Sales Income',
    '4030-WALKIN' => 'Walk-In Income',
    '4040-CROSSFIT' => 'Crossfit Income',
    '4050-YOGA' => 'Yoga Income',
    '4060-ZUMBA' => 'Zumba Income',
    '4070-OTHER' => 'Other Income'
];

$income_data = [];
$total_income = 0;

foreach($income_categories as $code => $name) {
    $query = $this->db->query("
        SELECT 
            COALESCE(SUM(`amount`),0) as total,
            COUNT(*) as count
        FROM `tbl_cash_receipts_journal`
        WHERE `account_code` = '$code'
        AND `date` BETWEEN '$from_date' AND '$to_date'
    ");
    $result = $query->getRow();
    $income_data[$code] = [
        'name' => $name,
        'total' => $result->total,
        'count' => $result->count
    ];
    $total_income += $result->total;
}

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Income Breakdown Report');

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'CASH RECEIPTS JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Income Breakdown Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Income Summary
$pdf->SetFont('Times', 'B', 11);
$pdf->Cell(0, 8, 'INCOME SUMMARY', 0, 1, 'L');
$pdf->Ln(2);

$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(80, 8, 'Income Category', 1, 0, 'C');
$pdf->Cell(50, 8, 'Transactions', 1, 0, 'C');
$pdf->Cell(60, 8, 'Total Amount (PHP)', 1, 1, 'C');

$pdf->SetFont('Times', '', 9);

foreach($income_data as $code => $data) {
    if($data['total'] > 0) {
        $pdf->Cell(80, 7, $data['name'] . ' (' . $code . ')', 1, 0, 'L');
        $pdf->Cell(50, 7, $data['count'], 1, 0, 'C');
        $pdf->Cell(60, 7, number_format($data['total'], 2), 1, 1, 'R');
    }
}

$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(130, 8, 'TOTAL INCOME', 1, 0, 'R');
$pdf->Cell(60, 8, number_format($total_income, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>