<?php
$this->request = \Config\Services::request();
$this->db = \Config\Database::connect();
$from_date = $this->request->getPostGet('from_date');
$to_date = $this->request->getPostGet('to_date');
$this->session = session();
$this->cuser = $this->session->get('__xsys_myuserzicas__');
require APPPATH . 'ThirdParty/fpdf/fpdf.php';

if(empty($from_date)) {
    $from_date = date('Y-m-01');
}
if(empty($to_date)) {
    $to_date = date('Y-m-t');
}

$formattedFrom = date('F d, Y', strtotime($from_date));
$formattedTo = date('F d, Y', strtotime($to_date));

// Fetch all receipts with running balance
$query = $this->db->query("
    SELECT
        `date`,
        `transaction_id`,
        `journal_id`,
        `account_code`,
        `amount`
    FROM
        `tbl_cash_receipts_journal`
    WHERE
        `date` BETWEEN '$from_date' AND '$to_date'
    ORDER BY
        `date` ASC,
        `journal_id` ASC
");

$receipts = $query->getResultArray();

$total_amount = $this->db->query("
    SELECT COALESCE(SUM(`amount`),0) as total 
    FROM `tbl_cash_receipts_journal` 
    WHERE `date` BETWEEN '$from_date' AND '$to_date'
")->getRow()->total;

$pdf = new FPDF('L', 'mm', 'A4');
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetTitle('Cash Receipts Journal Report');

// Get page width and set margins
$page_width = $pdf->GetPageWidth();
$left_margin = 10;
$right_margin = 10;
$available_width = $page_width - $left_margin - $right_margin;

// Calculate column widths (percentages of available width)
// Date: 12%, Trans ID: 20%, Journal ID: 12%, Account Code: 20%, Amount: 16%, Running Balance: 20%
$col_widths = [
    $available_width * 0.12,   // Date
    $available_width * 0.20,   // Transaction ID
    $available_width * 0.12,   // Journal ID
    $available_width * 0.20,   // Account Code
    $available_width * 0.16,   // Amount
    $available_width * 0.20    // Running Balance
];

$pdf->SetX($left_margin);

// Header
$pdf->SetFont('Times', 'B', 16);
$pdf->Cell(0, 10, 'CASH RECEIPTS JOURNAL', 0, 1, 'C');
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0, 6, 'Main Journal Report', 0, 1, 'C');
$pdf->SetFont('Times', 'I', 10);
$pdf->Cell(0, 6, 'Date Range: ' . $formattedFrom . ' - ' . $formattedTo, 0, 1, 'C');
$pdf->Ln(8);

// Table Header
$pdf->SetFont('Times', 'B', 9);
$pdf->SetX($left_margin);
$pdf->Cell($col_widths[0], 8, 'Date', 1, 0, 'C');
$pdf->Cell($col_widths[1], 8, 'Transaction ID', 1, 0, 'C');
$pdf->Cell($col_widths[2], 8, 'Journal ID', 1, 0, 'C');
$pdf->Cell($col_widths[3], 8, 'Account Code', 1, 0, 'C');
$pdf->Cell($col_widths[4], 8, 'Amount (PHP)', 1, 0, 'C');
$pdf->Cell($col_widths[5], 8, 'Running Balance', 1, 1, 'C');

// Data rows with running balance
$pdf->SetFont('Times', '', 9);
$running_balance = 0;

foreach($receipts as $row) {
    $running_balance += $row['amount'];
    
    $pdf->SetX($left_margin);
    $pdf->Cell($col_widths[0], 7, date('Y-m-d', strtotime($row['date'])), 1, 0, 'C');
    $pdf->Cell($col_widths[1], 7, $row['transaction_id'], 1, 0, 'L');
    $pdf->Cell($col_widths[2], 7, $row['journal_id'], 1, 0, 'C');
    $pdf->Cell($col_widths[3], 7, $row['account_code'], 1, 0, 'L');
    $pdf->Cell($col_widths[4], 7, number_format($row['amount'], 2), 1, 0, 'R');
    $pdf->Cell($col_widths[5], 7, number_format($running_balance, 2), 1, 1, 'R');
}

// Grand Total row
$pdf->SetFont('Times', 'B', 9);
$pdf->SetX($left_margin);
$pdf->Cell($col_widths[0] + $col_widths[1] + $col_widths[2] + $col_widths[3], 8, 'GRAND TOTAL', 1, 0, 'R');
$pdf->Cell($col_widths[4], 8, number_format($total_amount, 2), 1, 0, 'R');
$pdf->Cell($col_widths[5], 8, number_format($running_balance, 2), 1, 1, 'R');

// Footer
$pdf->SetY(-20);
$pdf->SetFont('Times', 'I', 8);
$pdf->Cell(0, 5, 'Generated by: ' . $this->cuser, 0, 0, 'L');
$pdf->Cell(0, 5, 'Page ' . $pdf->PageNo() . ' of {nb}', 0, 1, 'R');

$pdf->Output();
exit;
?>